@port = 8092

### 同步项目
Get http://{{host}}:{{port}}/projects/sync
access-token: {{accessToken}}


### 获取领导下属树结构 zhanghao 10S01029 
Get http://{{host}}:{{port}}/users/subordinates/10S01029
access-token: {{accessToken}}

### 获取领导下属树结构 linwenqin 10S02445
Get http://{{host}}:{{port}}/users/subordinates/10S02445
access-token: {{accessToken}}


### 获取领导下属树结构 10S01029 张皓 10S00772 黄力 10S00760 钟启兴 10S00980 谭广华
Get http://{{host}}:{{port}}/vorg/subordinates/10S00772
access-token: {{accessToken}}

// 10S03581 10S03421 10S02951 10S02193 10S01894 10S01892 10S01832 10S00772


### 添加部门预估工时
Post http://{{host}}:{{port}}/dept_estimate
Content-Type: application/json
access-token: {{accessToken}}

{
  "project_id": 1,
  "uid": "uidq2225",
  "year": "2021",
  "estimate_hour": [1,2,3,4,5,6,7,8,9,10,11,12]
}

### 获取部门预估工时
Get http://{{host}}:{{port}}/dept_estimate?uid=uidq2225&year=2020
access-token: {{accessToken}}

### 修改部门预估工时
Put http://{{host}}:{{port}}/dept_estimate/3
Content-Type: application/json
access-token: {{accessToken}}

{
  "uid": "uidq2226",
  "estimate_hour": [0,2,3,4,5,6,7,8,9,10,11,12],
  "year": 2020,
  "project_id": 3
}

### 删除部门预估工时
DELETE http://{{host}}:{{port}}/dept_estimate/3
access-token: {{accessToken}}



### 获取项目类型
Get http://{{host}}:{{port}}/project_type?status=1
access-token: {{accessToken}}

### 根据项目类型获取项目
Get http://{{host}}:{{port}}/projects?project_type=1
access-token: {{accessToken}}


### 获取学科
Get http://{{host}}:{{port}}/discipline
access-token: {{accessToken}}



### 获取项目&项目工时
Get http://{{host}}:{{port}}/project_estimate/projects?project_type=1&source_system=1
access-token: {{accessToken}}

### 添加项目预估工时
Post http://{{host}}:{{port}}/project_estimate
Content-Type: application/json
access-token: {{accessToken}}

{
  "project_id": 1,
  "discipline_id": "1",
  "year": "2020",
  "estimate_hour": [1,2,3,4,5,6,7,8,9,10,11,12]
}

### 获取项目预估工时
Get http://{{host}}:{{port}}/project_estimate/projects?project_type=1
access-token: {{accessToken}}



### 获取项目记录工时
Get http://{{host}}:{{port}}/project_record
access-token: {{accessToken}}

### 按部门统计，获取部门内不同组别，对应的预估工时、考勤工时、填写工时
Get http://{{host}}:{{port}}/statistics/department/manhours?year=2020
access-token: {{accessToken}}


### 添加埋点
Post http://{{host}}:{{port}}/analytics/point_info
Content-Type: application/json
access-token: {{accessToken}}

{
  "page_id": 1001
}

### 获取组织Tree
Get http://10.219.107.250/hololens/api/v1/resource-plan/orgnazition/tree?org_id=1
access-token: {{accessToken}}

### 53 68
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/project_view?org_id=55&start_year=2021&start_month=1&end_year=2021&end_month=12
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/member_month?org_id=55&uid=uidp5340&year=2021&month=2
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/org_summary?org_id=1&start_year=2019&start_month=01&end_year=2020&end_month=12&project_id=1
access-token: {{accessToken}}


###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/orgnazition_view?org_id=53&start_year=2021&start_month=1&end_year=2021&end_month=12
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/orgnazition/tree?org_id=1
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/orgResource?org_id=53&year=2021&month=1
access-token: {{accessToken}}

###
Post http://10.219.107.250/hololens/api/v1/resource-plan/orgResource
Content-Type: application/json
access-token: {{accessToken}}

{
  "org_id": 55,
  "year": 2020,
  "month": 12,
  "member_plan": 61
}


###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/member_projects?org_id=55&year=2020&month=12&uid=uidq0971
access-token: {{accessToken}}


###
Get http://10.219.107.250/hololens/api/v1/resource-plan/orgnazition
access-token: {{accessToken}}


###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_chart/org_res_deviation?org_id=1&start_year=2019&start_month=1&end_year=2021&end_month=1
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/almProjects?project_id=1
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/almProjects?estimated_start_date=2018-01-01&completion_date=2018-12-30
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/almProjects/all_project_type
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/organization/members/search?org_id=1
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/organization/members/search?org_id=1
access-token: {{accessToken}}

###
Delete http://10.219.107.250/hololens/api/v1/resource-plan/org_estimates/project?org_id=55&year=2021&month=3&project_id=324
access-token: {{accessToken}}

###
Get http://10.219.107.250/hololens/api/v1/resource-plan/org_estimate_query/members?org_id=55&project_id=324&year=2021&month=3
access-token: {{accessToken}}
