### 获取alm所有项目
GET http://localhost:8084/bu/CT/projects
### 获取alm中某个项目的工时记录
GET http://localhost:8084/projects/PMD20200227001_G6SA_R2_H3N_Upgrade/work_records
### 获取alm中某个group的项目
GET http://localhost:8084/projects/PMD20200227001_G6SA_R2_H3N_Upgrade/work_records



### 获取plm所有项目
Get http://localhost:8088/business_units/CT/projects
### 获取plm中某个项目的工时记录
Get http://localhost:8088/projects/PMD20180822001/work_records?date=202004



### 获取man hour中所有项目
Get http://localhost:8086/statistics/project_item/man_hour/PMD20180823002PTV
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff
### 获取用户工作记录
Get http://localhost:8086/users/uidq2225/work_records
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff
### 获取用户工作负荷
Get http://localhost:8086/users/uidq2225/work_load
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff
### 查询某个部门填写的工时与考勤工时的对比情况
Get http://localhost:8086/statistics/department/man_hour?is_grouping=0&date=202001
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff
### 获取某个部门||某个人的考勤工时
GET http://localhost:8086/statistics/department/man_hour?department=CT_DES_DIP&is_grouping=0&date=202006
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff
### 获取项目列表
GET http://localhost:8086/projects
access-token: ef9a2034-192c-4fe6-b171-e0852dddedff




