###
Post https://itc.desaysv.com/devminus/assistant/api/v1/devices
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5
Content-Type: application/json

{
  "device_no": "haha1",
  "category_id": 1,
  "device_name": "haha"
}

###
Put https://itc.desaysv.com/devminus/assistant/api/v1/devices/haha1
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5
Content-Type: application/json

{
  "supplier": "supplier111"
}

###
Get https://itc.desaysv.com/devminus/assistant/api/v1/devices?device_no=haha1
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5


###
DELETE https://itc.desaysv.com/devminus/assistant/api/v1/devices/haha1
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5

###
Get https://itc.desaysv.com/devminus/assistant/api/v1/devices/qr_code?device_no=haha&qr_type=0
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5


###
Get https://itc.desaysv.com/devminus/assistant/api/v1/devices_categories
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5

###
Get https://itc.desaysv.com/devminus/assistant/api/v1/devices_user_rs/uidq2225
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5

###
Post https://itc.desaysv.com/devminus/assistant/api/v1/device_borrow_records/borrow
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5
Content-Type: application/json

{
  "device_no": "haha"
}


###
Post https://itc.desaysv.com/devminus/assistant/api/v1/device_borrow_records/return/user
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5
Content-Type: application/json

{
  "device_no": "haha"
}


###
Post https://itc.desaysv.com/devminus/assistant/api/v1/device_borrow_records/return/admin
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5
Content-Type: application/json

{
  "device_no": "haha"
}


###
Get https://itc.desaysv.com/devminus/assistant/api/v1/device_borrow_records?device_no=haha
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5