###
Get https://itc.desaysv.com/devminus/assistant/api/v1/auth/public_key
access_token: 5005f9fe-fb4c-4520-8e8d-ee436f00dff5


###
Post https://itc.desaysv.com/devminus/assistant/api/v1/auth/open_id


###
Put https://itc.desaysv.com/devminus/assistant/api/v1/auth/secret_key

###
Get https://itc.desaysv.com/devminus/assistant/api/v1/auth/login_info?access_token=0a6c08e9-1ca6-46ea-af31-f89e7fec3268


###
Get https://itc.desaysv.com/devminus/auth/publicKey

###
Post https://itc.desaysv.com/devminus/auth/openId

###
Post https://itc.desaysv.com/devminus/test/uidq2225/23
access-token: {{accessToken}}

{
  "device_no": "haha",
  "category_id": 1,
  "device_name": "haha"
}

### 迁移接口
GET https://itc.desaysv.com/devminus/assistant/migrate


### test
POST https://itc.desaysv.com/devminus/test
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

syz
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="age"

66
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imgData"; filename="11.jpg"

< ../../assets/img/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--






