@moduleName = resource-plan
@createdAt = {{$datetime iso8601}}

### 获取领导下属树结构 10S01029 张皓 10S00772 黄力 10S00760 钟启兴 10S00980 谭广华
Get https://{{host}}{{baseUrl}}/{{moduleName}}/vorg/subordinates/10S00772
access-token: {{accessToken}}

### 
Get https://{{host}}{{baseUrl}}/{{moduleName}}/statistics/department/manhours?year=2020
access-token: {{accessToken}}